name: test and build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  npm-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: install dependencies
        run: npm ci
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: install dependencies 
        run: npm ci
      - name: Test code
        run: npm run test -- --browsers ChromeHeadless --watch=false
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: install dependencies 
        run: npm ci
      - name: Build Code
        run: npm run build
      - name: Deploy code
        run:  echo "Deploying...."
